model_config_list: {
config: {
name: "vae_encoder",
base_path: "/home/models/encoder/",
model_platform: "tensorflow"
},
config: {
name: "vae_decoder",
base_path: "/home/models/decoder/",
model_platform: "tensorflow"
},
config: {
name: "dialog",
base_path: "/home/models/dialog/",
model_platform: "tensorflow"
},
}
